// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJr7AHkInTv-Dn4puJn_3MgVRsklI7nOQ',
    appId: '1:902800556396:web:7c7acb28d16000a800b349',
    messagingSenderId: '902800556396',
    projectId: 'iot-lab-sads',
    authDomain: 'iot-lab-sads.firebaseapp.com',
    storageBucket: 'iot-lab-sads.appspot.com',
    measurementId: 'G-KKJTN6RYPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFqeW-0FTEIlftFJBJrhbFNUfu44UzkA',
    appId: '1:902800556396:android:3b78e7b78a79429000b349',
    messagingSenderId: '902800556396',
    projectId: 'iot-lab-sads',
    storageBucket: 'iot-lab-sads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg2oY4_y9VxqFshL8QZcdQTZJ328m2jK8',
    appId: '1:902800556396:ios:7a6d0732c37b3a5300b349',
    messagingSenderId: '902800556396',
    projectId: 'iot-lab-sads',
    storageBucket: 'iot-lab-sads.appspot.com',
    iosBundleId: 'com.example.beaconSimulator',
  );

}